version: "3.8"

services:
  postgres:
    container_name: gestao_vagas_pg
    image: bitnami/postgresql
    ports:
      - 5431:5432
    environment:
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=admin
      - POSTGRESQL_DATABASE=gestao_vagas